### ISSUE TITLE
UberMovement problems

### ISSUE THREAD

**Issue by ThomasRigoni7** [ArsamAryandoust/EnergyTransitionTasks#123]
London city zones start with cord_0 while all other present cities start with cord_1:

city, city_id
Guadalajara,0
Stockholm,1
San Francisco,2
Auckland,3
Boston,4
Brussels,5
London,6
Miami,7
Leeds,8
Tampa Bay,9
Hyderabad,10
Sao Paulo,11
Seattle,12
Bangalore,13

Will have to remove temporary fix in UniversalGNN when working with updated dataset

**Comment by ArsamAryandoust** [comment]
London starts at 0. Is now shifted to start at 1.
Sydney starts at 2. Is now shifted to start at 1.

All cities should start at 1 now, Ser..
